# Generated by Django 3.0.8 on 2020-08-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='gameMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.TextField(default=' , , , , , , , , ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.liveGame')),
            ],
        ),
    ]
