# Generated by Django 3.0.8 on 2020-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemoves',
            name='moves',
            field=models.TextField(default='[ , , , , , , , , ]'),
        ),
        migrations.AlterField(
            model_name='livegame',
            name='gameId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
