# Generated by Django 3.0.8 on 2020-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200803_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemoves',
            name='moves',
            field=models.TextField(default="['','','','','','','','','']"),
        ),
    ]
