# Generated by Django 3.0.8 on 2020-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200804_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemoves',
            name='player',
            field=models.CharField(default='O', max_length=1),
        ),
    ]
