# Generated by Django 3.0.8 on 2020-08-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gameMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemyMoves', models.TextField(default='     ,       ')),
                ('playerMoves', models.TextField(default='     ,       ')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battleship.gameSession')),
            ],
        ),
    ]
