# Generated by Django 3.0.8 on 2020-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemoves',
            name='enemyMoves',
            field=models.TextField(default='       ,     '),
        ),
        migrations.AlterField(
            model_name='gamemoves',
            name='playerMoves',
            field=models.TextField(default='       ,     '),
        ),
    ]
