# Generated by Django 3.0.8 on 2020-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0003_auto_20200805_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemoves',
            name='enemyShots',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamemoves',
            name='playerShots',
            field=models.TextField(default=''),
        ),
    ]
