# Generated by Django 3.0.8 on 2020-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0004_auto_20200806_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemoves',
            name='turn',
            field=models.CharField(default='p', max_length=1),
        ),
    ]
