# Generated by Django 3.0.8 on 2020-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0006_auto_20200807_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemoves',
            name='eSunk',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamemoves',
            name='pSunk',
            field=models.TextField(default=''),
        ),
    ]
